[workspace]
members = [
    # core
    "toggl-core",
    "toggl",

    # API implementations
    "toggl-api",
    "toggl-reports", 
    "toggl-webhooks",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Stefan Ruzitschka <stefan@icepuma.dev>"]
repository = "https://github.com/icepuma/toggl-rs"
license = "WTFPL"
version = "0.0.3"

[workspace.dependencies]
# External dependencies
reqwest = { version = "0.12", features = ["json", "blocking", "multipart"] }
thiserror = "2"
url = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
owo-colors = "4"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"

# Dev dependencies
mockito = "1"
pretty_assertions = "1"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }

# Internal dependencies
toggl-core = { path = "toggl-core", version = "0.0.3" }
toggl-api = { path = "toggl-api", version = "0.0.3" }
toggl-reports = { path = "toggl-reports", version = "0.0.3" }
toggl-webhooks = { path = "toggl-webhooks", version = "0.0.3" }